In [1]:
import wikipedia
from bs4 import BeautifulSoup
import re
import pandas as pd
import glob

In [3]:
file_list = glob.glob('data_RAE/athletes*')

In [4]:
pd.read_csv('data_RAE/athletes_1990-1991.txt', sep='\t')

,No,Family Name,Given Name,Nation,Races,World CupRank,Rank(avg),Points(avg),Wins,2nd,...,Podiums,Top5s,Top10s,Top20s,Top30s,Top40s,>40,LAP,DNF,DSQ
0,1,Kirchner,Mark,GER,14,2.0,9.1,15.9,4,0,...,6,7,10,13,13,13,1,0,0,0
1,2,Tchepikov,Sergei,URS,12,1.0,8.9,16.5,3,1,...,4,8,8,11,11,12,0,0,0,0
2,3,Luck,Frank,GER,10,4.0,9.3,16.0,1,3,...,4,5,7,9,9,10,0,0,0,0
3,4,Carrara,Pieralberto,ITA,13,5.0,21.0,10.6,1,1,...,3,4,5,8,9,11,2,0,0,0
4,5,Tarasov,Sergei Sen.,URS,10,10.0,10.6,11.4,1,1,...,2,3,6,7,9,9,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,182,Milliken,Kevin,CAN,1,NaN,45.0,0.0,0,0,...,0,0,0,0,0,0,1,0,0,0
182,183,Janke,Todd,CAN,1,NaN,53.0,0.0,0,0,...,0,0,0,0,0,0,1,0,0,0
183,184,Mazilu,Dan,ROM,4,NaN,73.3,0.0,0,0,...,0,0,0,0,0,0,4,0,0,0
184,185,Bridgford,Lindsay,AUS,12,NaN,77.3,0.0,0,0,...,0,0,0,0,0,0,12,0,0,0
185,186,Paul,Andrew,AUS,7,NaN,71.6,0.0,0,0,...,0,0,0,0,0,0,7,0,0,0

In [5]:
athlete = 'Stephane Bouthiaux'
tmp = wikipedia.WikipediaPage('Stephane Bouthiaux').html()

In [6]:
soup = BeautifulSoup(tmp, 'html.parser')
indiatable=soup.find('span',{'class':"bday"})
indiatable = str(indiatable)

In [7]:
pattern = '[0-9]+-[0-9]+-[0-9]+'
dob = re.findall(pattern, indiatable)

if len(dob) == 1:
    dob = dob[0]
    print(dob)
else:
    print('problem with', athlete)

1966-03-26